# SPDX-FileCopyrightText: Copyright (c) 2014-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.2.2
  SuggestExtensions: false
  NewCops: enable
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 10
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/BlockLength:
  Max: 50
require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
