AllCops:
  Exclude:
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.2.2
  SuggestExtensions: false
  NewCops: enable

Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 10
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/BlockLength:
  Max: 50
