# SPDX-FileCopyrightText: Copyright (c) 2014-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/ruby
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
  sudo apt-get update --fix-missing
  sudo apt-get install --yes subversion diffstat
  sudo apt-get install --yes software-properties-common
  sudo add-apt-repository -y ppa:git-core/ppa
  sudo apt-get update --fix-missing
  sudo apt-get remove -y git
  sudo apt-get install --yes git
merge:
  script: |
    bundle exec rake
release:
  pre: false
  script: |
    pdd --verbose --file=/dev/null
    bundle exec rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/hoc/version.rb
    git commit -m "${tag}" lib/hoc/version.rb
    gem build hoc.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
