---
name: codecov
'on':
  push:
    branches:
      - master
jobs:
  codecov:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - run: sudo apt install -y diffstat
      - run: bundle install
      - run: bundle exec rake
      - uses: codecov/codecov-action@v5
        with:
          files: coverage/.resultset.json
          fail_ci_if_error: true
