---
name: rake
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-24.04]
        ruby: [3.0, 2.7]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: sudo apt install -y diffstat
      - run: bundle update
      - run: bundle exec rake
